part of nepalpay_flutter;

class NepalPayConfig {
  NepalPayConfig.live({
    required this.amount,
    required this.instrumentCode,
    required this.merchantId,
    required this.merchantName,
    required this.merchantTxnId,
    required this.processId,
    required this.transactionRemarks,
    this.serverUrl=kNepalPayLiveUrl
  });


  NepalPayConfig.dev({
    required this.amount,
    required this.instrumentCode,
     this.merchantId = kDevMerchantId,
    required this.merchantName,
    required this.merchantTxnId,
    required this.processId,
    required this.transactionRemarks,
    this.serverUrl=kNepalPayDevUrl
  });

  /// server url: https://gateway.nepalpayment.com/Payment/Index
  String? serverUrl;
  double amount; /// The amount of the transaction.
  String instrumentCode; /// The code for the payment instrument being used.
  String? merchantId; /// E.g. 5248 The ID of the merchant requesting the transaction.
  String merchantName; /// E.g. salesberryapi The name of the merchant requesting the transaction.
  String merchantTxnId; /// The ID/Code/Product Description generated by the merchant for the transaction.
  String processId; /// The unique ID for the transaction process.
  String transactionRemarks; /// Any additional remarks or notes for the transaction.
}
